name: iOS KMP Guardian

# Se ejecutará cada vez que hagas push o un Pull Request a tus ramas principales
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-ios:
    name: Verificar compilación en iOS
    # ¡La magia! Le pedimos a GitHub que nos preste un Mac de sus servidores
    runs-on: macos-latest

    steps:
      - name: Descargar el código (Checkout)
        uses: actions/checkout@v4

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Asegúrate de que coincida con la que usas en local

      - name: Configurar caché de Gradle
        # Esto hace que las siguientes compilaciones sean mucho más rápidas
        uses: gradle/actions/setup-gradle@v3

      - name: Compilar binarios de iOS
        # Esta tarea compila el código de commonMain e iosMain para la arquitectura de simulador de Apple.
        # Si tienes errores de sintaxis o librerías incompatibles con iOS, fallará aquí.
        # Nota: Ajusta 'composeApp' si el módulo principal de tu proyecto tiene otro nombre.
        run: ./gradlew :composeApp:compileKotlinIosX64